import Foundation

LumaShaderCompiler.main()

/// Translates each authored effect in `Shaders/` into the forms the frontends
/// consume: a Swift catalog of the GLSL, which the GTK host hands to its
/// `luma_shader_effect` widget, and a Metal fragment function for the SwiftUI
/// host. Authors write the effect once, body-only, against the uniform
/// vocabulary the preamble below declares.
struct LumaShaderCompiler {
    static let preamble = """
        #version 450
        layout(location = 0) in vec2 v_uv;
        layout(location = 0) out vec4 frag_color;
        layout(binding = 0) uniform ShaderEffectUniforms {
            vec2 u_resolution;
            float u_time;
            float u_scheme;
        };

        """

    static func main() {
        let options = Options(arguments: CommandLine.arguments)
        let effects = effects(in: options.shaderDir)
        let bodies = effects.map { try! String(contentsOf: $0.source, encoding: .utf8) }

        if let swiftOut = options.swiftOut {
            write(swiftCatalog(of: effects, bodies: bodies), to: swiftOut)
        }
        if let metalDir = options.metalDir {
            for (effect, body) in zip(effects, bodies) {
                let fragment = metalFragment(named: effect.metalFunction, body: body)
                write(fragment, to: metalDir.appendingPathComponent("\(effect.metalFileName).metal"))
            }
        }
    }

    private static func effects(in directory: URL) -> [Effect] {
        let names = try! FileManager.default.contentsOfDirectory(atPath: directory.path)
        return names
            .filter { $0.hasSuffix(Effect.suffix) }
            .sorted()
            .map { Effect(fileName: $0, directory: directory) }
    }

    private static func swiftCatalog(of effects: [Effect], bodies: [String]) -> String {
        let entries = zip(effects, bodies).map { effect, body in
            let escaped = body
                .replacingOccurrences(of: "\\", with: "\\\\")
                .trimmingCharacters(in: .newlines)
                .split(separator: "\n", omittingEmptySubsequences: false)
                .map { $0.isEmpty ? "" : "        \($0)" }
                .joined(separator: "\n")
            return """
                    public static let \(effect.swiftName) = \"\"\"
                \(escaped)
                        \"\"\"
                """
        }
        return """
            // This file is auto-generated by LumaShaderCompiler.

            /// The authored GLSL of each effect in `Shaders/`, body-only: the host
            /// widget supplies the version directive and the uniform declarations.
            public enum ShaderEffects {
            \(entries.joined(separator: "\n\n"))
            }

            """
    }

    private static func metalFragment(named name: String, body: String) -> String {
        let workDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("LumaShaderCompiler-\(name)", isDirectory: true)
        try! FileManager.default.createDirectory(at: workDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: workDir) }

        let glsl = workDir.appendingPathComponent("effect.frag")
        let spirv = workDir.appendingPathComponent("effect.spv")
        try! (preamble + body).write(to: glsl, atomically: true, encoding: .utf8)

        run("glslang", ["-V", glsl.path, "-o", spirv.path])
        return run("spirv-cross", [
            "--msl",
            "--rename-entry-point", "main", name, "frag",
            spirv.path,
        ])
    }

    private static func write(_ contents: String, to destination: URL) {
        try! FileManager.default.createDirectory(
            at: destination.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        guard (try? String(contentsOf: destination, encoding: .utf8)) != contents else { return }
        try! contents.write(to: destination, atomically: true, encoding: .utf8)
    }

    @discardableResult
    private static func run(_ tool: String, _ arguments: [String]) -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = [tool] + arguments
        let output = Pipe()
        process.standardOutput = output
        try! process.run()
        let data = output.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            FileHandle.standardError.write("LumaShaderCompiler: \(tool) failed\n".data(using: .utf8)!)
            exit(1)
        }
        return String(data: data, encoding: .utf8)!
    }

    struct Effect {
        static let suffix = ".frag.glsl"

        let swiftName: String
        let metalFunction: String
        let metalFileName: String
        let source: URL

        init(fileName: String, directory: URL) {
            let words = fileName.dropLast(Effect.suffix.count).split(separator: "-")
            swiftName = words.first! + words.dropFirst().map { $0.capitalized }.joined()
            metalFunction = swiftName + "Fragment"
            metalFileName = words.map { $0.capitalized }.joined() + "Fragment"
            source = directory.appendingPathComponent(fileName)
        }
    }

    /// `--metal-dir` is what pulls in glslang and spirv-cross, so hosts with no
    /// Metal to feed leave it off and need neither tool installed.
    private struct Options {
        let shaderDir: URL
        let swiftOut: URL?
        let metalDir: URL?

        init(arguments: [String]) {
            var values: [String: String] = [:]
            for index in stride(from: 1, to: arguments.count - 1, by: 2) {
                values[arguments[index]] = arguments[index + 1]
            }
            shaderDir = URL(fileURLWithPath: values["--shader-dir"]!)
            swiftOut = values["--swift-out"].map { URL(fileURLWithPath: $0) }
            metalDir = values["--metal-dir"].map { URL(fileURLWithPath: $0) }
        }
    }
}
